package CalculadoraUninorte;

import java.awt.event.WindowEvent;
import java.awt.event.WindowAdapter;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileNameExtensionFilter;

public class ventana extends javax.swing.JFrame {

    File historial = new File("Historial.txt");

    public ventana() {
        initComponents();
        setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);

        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent e) {
                //jFileChooser1.showSaveDialog(null);
                try {
                    File historial = new File("Historial.txt");
                    //historial = jFileChooser1.getSelectedFile();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Escoja un archivo");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de texto", "txt");
        jFileChooser1.setFileFilter(filtro);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Operando 1");

        jLabel2.setText("Operando 2");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setEnabled(false);
        jScrollPane2.setViewportView(jTextArea2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opción", "10**x", "Búsqueda", "Combinatoria", "Cos(x)", "Exponenciación**", "Factorial!", "Inverso de n(1/n)", "Log_10", "Logaritmo natural", "Módulo", "Pi", "Radicación", "Sen(x)", "Sort", "Tan(x)", "División/", "Multiplicación*", "Resta-", "Suma+", "Unario-", "X**2", "X**3" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel3.setText("Operación");

        jLabel4.setText("Resultado");

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jButton1.setText("Ans");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setLabel("Archivo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setEnabled(false);
        jButton3.setLabel("Archivo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setLabel("Exportar ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setLabel("Aceptar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setLabel("Clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Radianes");
        jCheckBox1.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox1))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5)
                            .addComponent(jLabel3)
                            .addComponent(jCheckBox1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)))
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        int index = jComboBox1.getSelectedIndex();
        if (index == 2 || index == 3 || index == 5 || index == 10 || index == 11 || index == 12 || index == 16 || index == 17 || index == 18 || index == 19) {
            jTextArea2.setEnabled(true);
            jButton3.setEnabled(true);
        } else {
            jTextArea2.setEnabled(false);
            jButton3.setEnabled(false);
        }
        if (index == 4 || index == 13 || index == 15) {
            jCheckBox1.setVisible(true);
        } else {
            jCheckBox1.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jFileChooser1.showOpenDialog(this);
        try {
            texto(jFileChooser1.getSelectedFile(), jTextArea1);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Escoja un archivo");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            switch (jComboBox1.getSelectedIndex()) {

                case 1: //10**                
                    jTextArea3.setText(Powers.potencia(new BigDecimal("10"), new BigDecimal(jTextArea1.getText())).toString());
                    break;
                case 2: //Búsqueda
                    jTextArea3.setText((Vector.buscar(leervector(jTextArea1.getText()), new BigDecimal(jTextArea2.getText()))));
                    break;
                case 3:         //Combinatoria
                    jTextArea3.setText(Discrete.combinatoria(new BigDecimal(jTextArea1.getText()), new BigDecimal(jTextArea2.getText())).toPlainString());
                    break;
                case 4: //Cos
                    jTextArea3.setText(Trigonometry.cos(jTextArea1.getText(), jCheckBox1.isSelected()).toString());
                    break;
                case 5://^
                    jTextArea3.setText(Powers.potencia(new BigDecimal(jTextArea1.getText()), new BigDecimal(jTextArea2.getText())).toString());
                    break;
                case 6: //!
                    jTextArea3.setText(Discrete.factorial(new BigDecimal(jTextArea1.getText())).toString());
                    break;
                case 7: //1/n
                    jTextArea3.setText(Arithmetic.inversoMultiplicativo(new BigDecimal(jTextArea1.getText())).toString());
                    break;
                case 8: //Log_10
                    jTextArea3.setText(Powers.LogBase10(new BigDecimal(jTextArea1.getText())).toString());
                    break;
                case 9: //Ln
                    jTextArea3.setText(Powers.Ln(new BigDecimal(jTextArea1.getText())).toString());
                    break;
                case 10:// mod
                    jTextArea3.setText(Arithmetic.modulo(new BigDecimal(jTextArea1.getText()), new BigDecimal(jTextArea2.getText())).toString());
                    break;
                case 11:// Pi
                    jTextArea3.setText(Trigonometry.PI(Long.parseLong(jTextArea1.getText())).toString());
                    break;
                case 12: // Raiz
                    jTextArea3.setText(Powers.Raiz(new BigDecimal(jTextArea1.getText()), new BigDecimal(jTextArea2.getText())).toString());
                    break;
                case 13: //Sen
                    jTextArea3.setText(String.valueOf(Trigonometry.sinus(jTextArea1.getText(), jCheckBox1.isSelected())));
                    break;
                case 14: //Sort                    
                    jTextArea3.setText(Astring((Vector.sort(leervector(jTextArea1.getText())))));
                    break;
                case 15: //Tan
                    jTextArea3.setText(Trigonometry.tan(new BigDecimal(jTextArea1.getText()), jCheckBox1.isSelected()).toString());
                    break;
                case 16: //División
                    jTextArea3.setText(Arithmetic.dividir(new BigDecimal(jTextArea1.getText()), new BigDecimal(jTextArea2.getText())).toString());
                    break;
                case 17: //multiplicación
                    jTextArea3.setText(Arithmetic.multiplicar(new BigDecimal(jTextArea1.getText()), new BigDecimal(jTextArea2.getText())).toString());
                    break;
                case 18: //Resta
                    jTextArea3.setText(Arithmetic.subtract(new BigDecimal(jTextArea1.getText()), new BigDecimal(jTextArea2.getText())).toString());
                    break;
                case 19: //Suma
                    jTextArea3.setText(Arithmetic.Suma(new BigDecimal(jTextArea1.getText()), new BigDecimal(jTextArea2.getText())).toString());
                    break;
                case 20:// unario-                    
                    jTextArea3.setText(Arithmetic.signMinus(new BigDecimal(jTextArea1.getText())));
                    break;
                case 21:// ^2                    
                    jTextArea3.setText(Powers.pot2(jTextArea1.getText()).toString());
                    break;
                case 22:// ^3
                    jTextArea3.setText(Powers.pot3(jTextArea1.getText()).toString());
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Seleccione una operación.");
                    break;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Entrada inválida");
        }

        try {
            Historial(historial, jTextArea3.getText());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Archivo de historial no encontrado");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jFileChooser1.showOpenDialog(this);
        try {
            texto(jFileChooser1.getSelectedFile(), jTextArea2);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Escoja un archivo");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jFileChooser1.showSaveDialog(this);
        try {
            Exportar(jFileChooser1.getSelectedFile(), jTextArea3);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Escoja un archivo");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Ans(new File("C:\\Users\\carlos\\Google Drive\\Complejidad\\Calculadora\\CalculadoraUninorte\\Historial.txt"), jTextArea1);
        } catch (IOException ex) {
            //JOptionPane.showMessageDialog(null, "Archivo de historial no encontrado");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTextArea1.setText(null);
        jTextArea2.setText(null);
        jTextArea3.setText(null);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public String Astring(ArrayList<BigDecimal> entrada) {
        String salida = "";
        for (int i = 0; i < entrada.size(); i++) {

            salida += entrada.get(i).toString();
            if (i != entrada.size() - 1) {
                salida += ", ";
            }
        }
        return salida;
    }

    public ArrayList<BigDecimal> leervector(String entrada) {
        ArrayList<BigDecimal> salida = new ArrayList<BigDecimal>();
        String[] partes = entrada.split(",");
        for (int i = 0; i < partes.length; i++) {
            salida.add(i, new BigDecimal(partes[i]));
        }
        return salida;
    }

    public void Ans(File archivo, JTextArea caja) throws FileNotFoundException, IOException {
        String linea = "", last;
        FileReader fr = new FileReader(archivo);
        BufferedReader br = new BufferedReader(fr);
        last = br.readLine();
        while (last != null) {
            linea = last;
            last = br.readLine();
        }
        caja.setText(linea);
    }

    public void texto(File archivo, JTextArea caja) throws FileNotFoundException, IOException {
        FileReader fr = new FileReader(archivo);
        BufferedReader br = new BufferedReader(fr);
        caja.setText(br.readLine());
    }

    public void Exportar(File archivo, JTextArea caja) throws FileNotFoundException, IOException {
        FileWriter fr = new FileWriter(archivo);
        BufferedWriter bw = new BufferedWriter(fr);
        bw.write(caja.getText());
        bw.close();
    }

    public void Historial(File archivo, String resultado) throws IOException {
        if (resultado != "") {
            PrintWriter wr = new PrintWriter(new FileOutputStream(archivo, true));
            wr.append(resultado);
            wr.append(System.getProperty("line.separator"));
            wr.close();
        }
    }

    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ventana().setVisible(true);

            }

        }
        );
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final javax.swing.JButton jButton1 = new javax.swing.JButton();
    private javax.swing.JButton jButton2;
    private static javax.swing.JButton jButton3;
    private static javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private static javax.swing.JComboBox jComboBox1;
    private static javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private static javax.swing.JTextArea jTextArea2;
    private static javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
