#include<iostream>
#include<conio.h>
#include<string.h>//hacer lo del menu =2
#include<iomanip>
#include<time.h>

using namespace std;
int casillasacertadas(int mat[100][100]){
    int w,s,contcasillas=0;
    for(w=1;w<=10;w++)
    {
        for(s=1;s<=10;s++)
        {
            if(mat[w][s]==90||mat[w][s]==80)
            {
                contcasillas=contcasillas+1;
            }
        }
    }
    return contcasillas;
}
      
int juego(int matriz[100][100],int cordx,int cordy){
    int q;
    if(matriz[cordx][cordy]==0)
    {
        q=99;
    }
    else
        if(matriz[cordx][cordy]==1)
        {
            if(matriz[cordx][cordy-4]==90&&matriz[cordx][cordy-3]==90&&matriz[cordx][cordy-2]==90&&matriz[cordx][cordy-1]==90)
            {
                q=80;
            }
            else
                if(matriz[cordx][cordy-3]==90&&matriz[cordx][cordy-2]==90&&matriz[cordx][cordy-1]==90&&matriz[cordx][cordy+1]==90)
                {
                    q=80;
                }
                else
                    if(matriz[cordx][cordy-2]==90&&matriz[cordx][cordy-1]==90&&matriz[cordx][cordy+1]==90&&matriz[cordx][cordy+2]==90)
                    {
                        q=80;
                    }
                    else
                        if(matriz[cordx][cordy-1]==90&&matriz[cordx][cordy+1]==90&&matriz[cordx][cordy+2]==90&&matriz[cordx][cordy+3]==90)
                        {
                            q=80;
                        }
                        else
                            if(matriz[cordx][cordy+1]==90&&matriz[cordx][cordy+2]==90&&matriz[cordx][cordy+3]==90&&matriz[cordx][cordy+4]==90)
                            {
                                q=80;
                            }
                            else
                                if(matriz[cordx-4][cordy]==90&&matriz[cordx-3][cordy]==90&&matriz[cordx-2][cordy]==90&&matriz[cordx-1][cordy]==90)
                                {
                                    q=80;
                                }
                                else
                                    if(matriz[cordx-3][cordy]==90&&matriz[cordx-2][cordy]==90&&matriz[cordx-1][cordy]==90&&matriz[cordx+1][cordy]==90)
                                    {
                                        q=80;
                                    }
                                    else
                                        if(matriz[cordx-2][cordy]==90&&matriz[cordx-1][cordy]==90&&matriz[cordx+1][cordy]==90&&matriz[cordx+2][cordy]==90)
                                        {
                                            q=80;
                                        }
                                        else
                                            if(matriz[cordx-1][cordy]==90&&matriz[cordx+1][cordy]==90&&matriz[cordx+2][cordy]==90&&matriz[cordx+3][cordy]==90)
                                            {
                                                q=80;
                                            }
                                            else
                                                if(matriz[cordx+1][cordy]==90&&matriz[cordx+2][cordy]==90&&matriz[cordx+3][cordy]==90&&matriz[cordx+4][cordy]==90)
                                                {
                                                    q=80;
                                                }
                                                else
                                                {
                                                    q=90;
                                                }
        }
        else
            if(matriz[cordx][cordy]==2)
            {
                if(matriz[cordx][cordy-4]==90&&matriz[cordx][cordy-3]==90&&matriz[cordx][cordy-2]==90&&matriz[cordx][cordy-1]==90)
                {
                    q=80;
                }
                else
                    if(matriz[cordx][cordy-3]==90&&matriz[cordx][cordy-2]==90&&matriz[cordx][cordy-1]==90&&matriz[cordx][cordy+1]==90)
                    {
                        q=80;
                    }
                    else
                        if(matriz[cordx][cordy-2]==90&&matriz[cordx][cordy-1]==90&&matriz[cordx][cordy+1]==90&&matriz[cordx][cordy+2]==90)
                        {
                            q=80;
                        }
                        else
                            if(matriz[cordx][cordy-1]==90&&matriz[cordx][cordy+1]==90&&matriz[cordx][cordy+2]==90&&matriz[cordx][cordy+3]==90)
                            {
                                q=80;
                            }
                            else
                                if(matriz[cordx][cordy+1]==90&&matriz[cordx][cordy+2]==90&&matriz[cordx][cordy+3]==90&&matriz[cordx][cordy+4]==90)
                                {
                                    q=80;
                                }
                                else
                                    if(matriz[cordx-4][cordy]==90&&matriz[cordx-3][cordy]==90&&matriz[cordx-2][cordy]==90&&matriz[cordx-1][cordy]==90)
                                    {
                                        q=80;
                                    }
                                    else
                                        if(matriz[cordx-3][cordy]==90&&matriz[cordx-2][cordy]==90&&matriz[cordx-1][cordy]==90&&matriz[cordx+1][cordy]==90)
                                        {
                                            q=80;
                                        }
                                        else
                                            if(matriz[cordx-2][cordy]==90&&matriz[cordx-1][cordy]==90&&matriz[cordx+1][cordy]==90&&matriz[cordx+2][cordy]==90)
                                            {
                                                q=80;
                                            }
                                            else
                                                if(matriz[cordx-1][cordy]==90&&matriz[cordx+1][cordy]==90&&matriz[cordx+2][cordy]==90&&matriz[cordx+3][cordy]==90)
                                                {
                                                    q=80;
                                                }
                                                else
                                                    if(matriz[cordx+1][cordy]==90&&matriz[cordx+2][cordy]==90&&matriz[cordx+3][cordy]==90&&matriz[cordx+4][cordy]==90)
                                                    {
                                                        q=80;
                                                    }
                                                    else
                                                    {
                                                        q=90;
                                                    }
            }
            else
                if(matriz[cordx][cordy]==3)
                {
                    if(matriz[cordx][cordy-2]==90&&matriz[cordx][cordy-1]==90)
                    {
                        q=80;
                    }
                    else
                        if(matriz[cordx][cordy-1]==90&&matriz[cordx][cordy+1]==90)
                        {
                            q=80;
                        }
                        else
                            if(matriz[cordx][cordy+1]==90&&matriz[cordx][cordy+2]==90)
                            {
                                q=80;
                            }
                            else
                                if(matriz[cordx-2][cordy]==90&&matriz[cordx-1][cordy]==90)
                                {
                                    q=80;
                                }
                                else
                                    if(matriz[cordx-1][cordy]==90&&matriz[cordx+1][cordy]==90)
                                    {
                                        q=80;
                                    }
                                    else
                                        if(matriz[cordx+1][cordy]==90&&matriz[cordx+2][cordy]==90)
                                        {
                                            q=80;
                                        }
                                        else
                                        {
                                            q=90;
                                        }
                }
                else
                    if(matriz[cordx][cordy]==4)
                    {
                        if(matriz[cordx][cordy-2]==90&&matriz[cordx][cordy-1]==90)
                        {
                            q=80;
                        }
                        else
                            if(matriz[cordx][cordy-1]==90&&matriz[cordx][cordy+1]==90)
                            {
                                q=80;
                            }
                            else
                                if(matriz[cordx][cordy+1]==90&&matriz[cordx][cordy+2]==90)
                                {
                                    q=80;
                                }
                                else
                                    if(matriz[cordx-2][cordy]==90&&matriz[cordx-1][cordy]==90)
                                    {
                                        q=80;
                                    }
                                    else
                                        if(matriz[cordx-1][cordy]==90&&matriz[cordx+1][cordy]==90)
                                        {
                                            q=80;
                                        }
                                        else
                                            if(matriz[cordx+1][cordy]==90&&matriz[cordx+2][cordy]==90)
                                            {
                                                q=80;
                                            }
                                            else
                                            {
                                                q=90;
                                            }
                    }
                    else
                        if(matriz[cordx][cordy]==5)
                        {
                            if(matriz[cordx][cordy-2]==90&&matriz[cordx][cordy-1]==90)
                            {
                                q=80;
                            }
                            else
                                if(matriz[cordx][cordy-1]==90&&matriz[cordx][cordy+1]==90)
                                {
                                    q=80;
                                }
                                else
                                    if(matriz[cordx][cordy+1]==90&&matriz[cordx][cordy+2]==90)
                                    {
                                        q=80;
                                    }
                                    else
                                        if(matriz[cordx-2][cordy]==90&&matriz[cordx-1][cordy]==90)
                                        {
                                            q=80;
                                        }
                                        else
                                            if(matriz[cordx-1][cordy]==90&&matriz[cordx+1][cordy]==90)
                                            {
                                                q=80;
                                            }
                                            else
                                                if(matriz[cordx+1][cordy]==90&&matriz[cordx+2][cordy]==90)
                                                {
                                                    q=80;
                                                }
                                                else
                                                {
                                                    q=90;
                                                }
                        }
                        else
                        {
                            q=80;
                        }
                        return q;
}
int cordenada(char cord){
    int t;
    if(cord=='A')
    {
        t=1;
    }
    else
        if(cord=='B')
        {
            t=2;
        }
        else
            if(cord=='C')
            {
                t=3;
            }
            else
                if(cord=='D')
                {
                    t=4;
                }
                else
                    if(cord=='E')
                    {
                        t=5;
                    }
                    else
                        if(cord=='F')
                        {
                            t=6;
                        }
                        else
                            if(cord=='G')
                            {
                                t=7;
                            }
                            else
                                if(cord=='H')
                                {
                                    t=8;
                                }
                                else
                                    if(cord=='I')
                                    {
                                        t=9;
                                    }
                                    else
                                        if(cord=='J')
                                        {
                                            t=10;
                                        }
                                        return t;
}
void main(){
    int m[100],ma1[100][100],ma12[100][100],ma2[100][100],ma22[100][100];//eliminar es solo para prueba;
    char x,v[100];
    int menu=0,h=0,ins1=0,ins2=0,tip,i,j,k=0,y,z,op,p,pos,xau,b=0,l=0,final=5,dislim=85,dis1=0,dis2=0;//Eliminar entes de i
    char nombres[5][100];
    v[1]='A';v[2]='B';v[3]='C';v[4]='D';v[5]='E';v[6]='F';v[7]='G';v[8]='H';v[9]='I';v[10]='J';
    m[1]=1;m[2]=2;m[3]=3;m[4]=4;m[5]=5;m[6]=6;m[7]=7;m[8]=8;m[9]=9;m[10]=10;
	system("color f0");
    srand(time(NULL));
    for(i=1;i<=10;i++)
    {
        for(j=1;j<=10;j++)
        {
            ma1[i][j]=0;
        }
    }
    for(i=1;i<=10;i++)
    {
        for(j=1;j<=10;j++)
        {
            ma12[i][j]=0;
        }
    }
    for(i=1;i<=10;i++)
    {
        for(j=1;j<=10;j++)
        {
            ma2[i][j]=0;
        }
    }
    for(i=1;i<=10;i++)
    {
        for(j=1;j<=10;j++)
        {
            ma22[i][j]=0;
        }
    }
    while(menu!=3&&h==0)
    {
        cout<<endl<<"                BATTLESHIP          ";
        cout<<endl<<"          ";
        cout<<endl<<"1. Jugador vs Jugador";
        cout<<endl<<"2. Jugador vs Computador";
        cout<<endl;
        cout<<endl<<"3. Salir del juego";
        cout<<endl<<"Escoja: ";
        cin>>menu;
		system("cls");
        if(menu==1)
        {
            cout<<endl<<"Ingrese los nombres de los jugadores";
            for(i=1;i<=2;i++)
            {
                cout<<endl<<"Nombre del jugador "<<i<<": ";
                cin>>nombres[i];
            }
             z=0;
			 system("cls");
            while(z<2)
            {
                z=z+1;
                k=0;
                cout<<endl<<"El jugador "<<nombres[z]<<" indique la ubicacion de sus naves "<<endl;
                cout<<endl;
                cout<<endl<<" Zona del mar propia"<<endl;
                cout<<"   ";
                for(i=1;i<=10;i++)
                {
                    cout<<setw(3)<<m[i];
                }
                cout<<endl;
                if(z==1)
                {
                    for(i=1;i<=10;i++)
                    {
                            cout<<setw(3)<<v[i];
                            for(j=1;j<=10;j++)
                            {
                                if(ma1[i][j]==0)
                                {
                                    cout<<setw(3)<<"-";
                                }
                            }
                            cout<<endl;
                    }
                }
                else
                    if(z==2)
                    {
                        for(i=1;i<=10;i++)
                        {
                            cout<<setw(3)<<v[i];
                            for(j=1;j<=10;j++)
                            {
                                if(ma2[i][j]==0)
                                {
                                    cout<<setw(3)<<"-";
                                }
                            }
                            cout<<endl;
                        }
                    }
                    op=0;
					system("pause");
                    while(op<3)
                    {
                        op=op+1;
                        cout<<endl<<"Tipos de naves que deben colocarse"<<endl;
                        cout<<"1.Portaviones (2 naves)"<<endl;
                        cout<<"2.Bote (3 naves)"<<endl;
                        cout<<"3.Lancha (5 naves)"<<endl;
                        cout<<endl;
						system("pause");
                        if(op==1)
                        {
                            p=1;
                            cout<<endl<<"Ubicacion del portaaviones: "<<p<<endl;//escribir que son 2 porta de 5 esp c/u
                            tip=1;
                        }
                        else
                            if(op==2)
                            {
                                b=1;
                                cout<<endl<<"Ubicacion del Buque "<<b<<endl;
                                tip=2;
                            }
                            else
                                if(op==3)
                                {
                                    l=1;
                                    cout<<endl<<"Ubicacion de la lancha "<<l<<endl;
                                    tip=3;
                                }
                                if(tip!=3)
                                {
                                    cout<<endl<<"Ingrese la coordenada donde lo ubicara: ";
                                    cin>>x;
                                    cin>>y;
                                    cout<<endl<<"desea colocarlo 1.Horizontal 2.Vertical: ";
                                    cin>>pos;
                                }
                                else
                                {
                                    cout<<endl<<"Ingrese la coordenada donde lo ubicara: ";
                                    cin>>x;
                                    cin>>y;
                                }
								system("cls");
                                xau=cordenada(x);
                                if(tip==1)
                                {
                                    p=0;
                                    while(p<=2)
                                    {
                                        p=p+1;
                                        k=k+1;
                                        if(pos==1)
                                        {
                                            if(z==1)
                                            {
                                                if(ma1[xau][y-2]==0&&ma1[xau][y-1]==0&&ma1[xau][y]==0&&ma1[xau][y+1]==0&&ma1[xau][y+2]==0)
                                                {
                                                    for(j=y-2;j<=y+2;j++)
                                                    {
                                                        ma1[xau][j]=k;
                                                    }
                                                }
                                                else
                                                {
                                                    cout<<endl<<"No se puede ubicar el bote en esa posicion, ingrese otra"<<endl;
                                                    p=p-1;
                                                    k=k-1;
                                                }
                                            }//termina z=1
                                            else
                                                if(z==2)
                                                {
                                                    if(ma2[xau][y-2]==0&&ma2[xau][y-1]==0&&ma2[xau][y]==0&&ma2[xau][y+1]==0&&ma2[xau][y+2]==0)
                                                    {
                                                        for(j=y-2;j<=y+2;j++)
                                                        {
                                                            ma2[xau][j]=k;
                                                        }
                                                    }
                                                    else
                                                    {
                                                        cout<<endl<<"No se puede ubicar el bote en esa posicion, ingrese otra"<<endl;
                                                        p=p-1;
                                                        k=k-1;
                                                    }
													system("pause");
                                                }//termina z=2
                                        }//termia pos1
                                        else
                                            if(pos==2)
                                            {
                                                if(z==1)
                                                {
                                                     if(ma1[xau-2][y]==0&&ma1[xau-1][y]==0&&ma1[xau][y]==0&&ma1[xau+1][y]==0&&ma1[xau+2][y]==0)
                                                    {
                                                        for(i=xau-2;i<=xau+2;i++)
                                                        {
                                                            ma1[i][y]=k;
                                                        }
                                                    }
                                                    else
                                                    {
                                                        cout<<endl<<"No se puede ubicar el bote en esa posicion, ingrese otra"<<endl;
                                                        p=p-1;
                                                        k=k-1;
                                                    }
                                                }//termina z 1
                                                else
                                                    if(z==2)
                                                    {
                                                        if(ma2[xau-2][y]==0&&ma2[xau-1][y]==0&&ma2[xau][y]==0&&ma2[xau+1][y]==0&&ma2[xau+2][y]==0)
                                                        {
                                                            for(i=xau-2;i<=xau+2;i++)
                                                            {
                                                                ma2[i][y]=k;
                                                            }
                                                        }
                                                        else
                                                        {
                                                            cout<<endl<<"No se puede ubicar el bote en esa posicion, ingrese otra"<<endl;
                                                            p=p-1;
                                                            k=k-1;
                                                        }
                                                    }
                                            }//pos 2
                                            else
                                            {
                                                cout<<endl<<"Ingrese bien los comandos";
                                                p=p-1;
                                            }
                                            if(z==1)
                                            {
                                                cout<<"   ";
                                                for(i=1;i<=10;i++)
                                                {
                                                    cout<<setw(3)<<m[i];
                                                }
                                                cout<<endl;
                                                for(i=1;i<=10;i++)
                                                {
                                                    cout<<setw(3)<<v[i];
                                                    for(j=1;j<=10;j++)
                                                    {
                                                        if(ma1[i][j]==0)
                                                        {
                                                            cout<<setw(3)<<"-";
                                                        }
                                                        else
                                                        {
                                                            cout<<setw(3)<<"P";
                                                        }
                                                    }
                                                    cout<<endl;
                                                }
                                            }
                                            else
                                                if(z==2)
                                                {
                                                    cout<<"   ";
                                                    for(i=1;i<=10;i++)
                                                    {
                                                        cout<<setw(3)<<m[i];
                                                    }
                                                    cout<<endl;
                                                    for(i=1;i<=10;i++)
                                                    {
                                                        cout<<setw(3)<<v[i];
                                                        for(j=1;j<=10;j++)
                                                        {
                                                            if(ma2[i][j]==0)
                                                            {
                                                                cout<<setw(3)<<"-";
                                                            }
                                                            else
                                                            {
                                                                cout<<setw(3)<<"P";
                                                            }
                                                        }
                                                        cout<<endl;
                                                    }
                                                }
                                                p=p+1;
												system("pause");
												system("cls");
                                                if(p<=2)
                                                {
                                                    cout<<endl<<"Ubicacion del portaaviones "<<p<<endl;
                                                    cout<<endl<<"Ingrese la coordenada donde lo ubicara: ";
                                                    cin>>x;
                                                    cin>>y;
                                                    cout<<endl<<"desea colocarlo 1.Horizontal 2.Vertical: ";
                                                    cin>>pos;
                                                    xau=cordenada(x);
                                                    p=p-1;
                                                }
												
                                    }//term,ina ciclo de porta
                                }//termina condicion tip 1
                                else
                                    if(tip==2)
                                    {
                                        b=0;
                                        while(b<=3)
                                        {
                                            b=b+1;
                                            k=k+1;
                                            if(pos==1)
                                            {
                                                if(z==1)
                                                {
                                                    if(ma1[xau][y-1]==0&&ma1[xau][y]==0&&ma1[xau][y+1]==0)
                                                    {
                                                        for(j=y-1;j<=y+1;j++)
                                                        {
                                                            ma1[xau][j]=k;
                                                        }
                                                    }
                                                    else
                                                    {
                                                        cout<<endl<<"No se puede ubicar la nave en esa posicion, ingrese otra"<<endl;
                                                        b=b-1;
                                                        k=k-1;
                                                    }
                                                }
                                                else
                                                    if(z==2)
                                                    {
                                                        if(ma2[xau][y-1]==0&&ma2[xau][y]==0&&ma2[xau][y+1]==0)
                                                        {
                                                            for(j=y-1;j<=y+1;j++)
                                                            {
                                                                ma2[xau][j]=k;
                                                            }
                                                        }
                                                        else
                                                        {
                                                            cout<<endl<<"No se puede ubicar la nave en esa posicion, ingrese otra"<<endl;
                                                            b=b-1;
                                                            k=k-1;
                                                        }  
                                                    }
                                            }//pos 1
                                            else
                                                if(pos==2)
                                                {
                                                    if(z==1)
                                                    {
                                                        if(ma1[xau-1][y]==0&&ma1[xau][y]==0&&ma1[xau+1][y]==0)
                                                        {
                                                            for(i=xau-1;i<=xau+1;i++)
                                                            {
                                                                ma1[i][y]=k;
                                                            }
                                                        }
                                                        else
                                                        {
                                                            cout<<endl<<"No se puede ubicar la nave en esa posicion, ingrese otra"<<endl;
                                                            b=b-1;
                                                            k=k-1;
                                                        }
                                                    }
                                                    else
                                                        if(z==2)
                                                        {
                                                            if(ma2[xau-1][y]==0&&ma2[xau][y]==0&&ma2[xau+1][y]==0)
                                                            {
                                                                for(i=xau-1;i<=xau+1;i++)
                                                                {
                                                                    ma2[i][y]=k;
                                                                }
                                                            }
                                                            else
                                                            {
                                                                cout<<endl<<"No se puede ubicar el bote en esa posicion, ingrese otra"<<endl;
                                                                b=b-1;
                                                                k=k-1;
                                                            }
                                                        }
                                                }//pos 2.
                                                else
                                                {
                                                    cout<<endl<<"Ingrese bien los comandos";
                                                    b=b-1;
                                                }
                                                if(z==1)
                                                {
                                                    cout<<"   ";
                                                    for(i=1;i<=10;i++)
                                                    {
                                                        cout<<setw(3)<<m[i];
                                                    }
                                                    cout<<endl;
                                                    for(i=1;i<=10;i++)
                                                    {
                                                        cout<<setw(3)<<v[i];
                                                        for(j=1;j<=10;j++)
                                                        {
                                                            if(ma1[i][j]==0)
                                                            {
                                                                cout<<setw(3)<<"-";
                                                            }
                                                            else
                                                                if(ma1[i][j]==1||ma1[i][j]==2)
                                                                {
                                                                    cout<<setw(3)<<'P';
                                                                }
                                                                else
                                                                {
                                                                    cout<<setw(3)<<"B";
                                                                }
                                                        }
                                                            cout<<endl;
                                                    }
                                                }
                                                else
                                                    if(z==2)
                                                    {
                                                        cout<<"   ";
                                                        for(i=1;i<=10;i++)
                                                        {
                                                            cout<<setw(3)<<m[i];
                                                        }
                                                        cout<<endl;
                                                        for(i=1;i<=10;i++)
                                                        {
                                                            cout<<setw(3)<<v[i];
                                                            for(j=1;j<=10;j++)
                                                            {
                                                                if(ma2[i][j]==0)
                                                                {
                                                                    cout<<setw(3)<<"-";
                                                                }
                                                                else
                                                                    if(ma2[i][j]==1||ma2[i][j]==2)
                                                                    {
                                                                        cout<<setw(3)<<'P';
                                                                    }
                                                                    else
                                                                    {
                                                                        cout<<setw(3)<<"B";
                                                                    }
                                                                }
                                                                cout<<endl;
                                                        }
                                                    }
                                                    b=b+1;
													system("pause");
													system("cls");
                                                    if(b<=3)
                                                    {
                                                        cout<<endl<<"Ubicacion del Buque "<<b<<endl;
                                                        cout<<endl<<"Ingrese la coordenada donde lo ubicara: ";
                                                        cin>>x;
                                                        cin>>y;
                                                        cout<<endl<<"desea colocarlo 1.Horizontal 2.Vertical: ";
                                                        cin>>pos;
                                                        xau=cordenada(x);
                                                        b=b-1;
                                                    }
                                        }//botes  while
                                    }//tip 2
                                    else
                                        if(tip==3)
                                        {
                                            l=0;
                                            while(l<=5)
                                            {
                                                l=l+1;
                                                k=k+1;
                                                if(z==1)
                                                {
                                                    if(ma1[xau][y]==0)
                                                    {
                                                        ma1[xau][y]=k;
                                                    }
                                                    else
                                                    {
                                                        cout<<endl<<"No se puede ubicar la nave en esa posicion, ingrese otra"<<endl;
                                                        l=l-1;
                                                        k=k-1;
                                                    }
                                                    cout<<"   ";
                                                    for(i=1;i<=10;i++)
                                                    {
                                                        cout<<setw(3)<<m[i];
                                                    }
                                                    cout<<endl;
                                                    for(i=1;i<=10;i++)
                                                    {
                                                        cout<<setw(3)<<v[i];
                                                        for(j=1;j<=10;j++)
                                                        {
                                                            if(ma1[i][j]==0)
                                                            {
                                                                cout<<setw(3)<<"-";
                                                            }
                                                            else
                                                                if(ma1[i][j]==1||ma1[i][j]==2)
                                                                {
                                                                    cout<<setw(3)<<'P';
                                                                }
                                                                else
                                                                    if(ma1[i][j]==3||ma1[i][j]==4||ma1[i][j]==5)
                                                                    {
                                                                        cout<<setw(3)<<'B';
                                                                    }
                                                                    else
                                                                    {
                                                                        cout<<setw(3)<<"L";
                                                                    }
                                                        }
                                                        cout<<endl;
                                                    }
                                                                                                                              
                                                }
                                                else
                                                    if(z==2)
                                                    {
                                                        if(ma2[xau][y]==0)
                                                        {
                                                            ma2[xau][y]=k;
                                                        }
                                                        else
                                                        {
                                                            cout<<endl<<"No se puede ubicar la nave en esa posicion, ingrese otra"<<endl;
                                                            l=l-1;
                                                            k=k-1;
                                                        }
                                                        cout<<"   ";
                                                        for(i=1;i<=10;i++)
                                                        {
                                                            cout<<setw(3)<<m[i];
                                                        }
                                                        cout<<endl;
                                                        for(i=1;i<=10;i++)
                                                        {
                                                            cout<<setw(3)<<v[i];
                                                            for(j=1;j<=10;j++)
                                                            {
                                                                if(ma2[i][j]==0)
                                                                {
                                                                    cout<<setw(3)<<"-";
                                                                }
                                                                else
                                                                    if(ma2[i][j]==1||ma2[i][j]==2)
                                                                    {
                                                                        cout<<setw(3)<<'P';
                                                                    }
                                                                    else
                                                                        if(ma2[i][j]==3||ma2[i][j]==4||ma2[i][j]==5)
                                                                        {
                                                                            cout<<setw(3)<<'B';
                                                                        }
                                                                        else
                                                                            {
                                                                                cout<<setw(3)<<"L";
                                                                            }
                                                            }
                                                            cout<<endl;
                                                        }
                                                    }
                                                    l=l+1;
													system("pause");
													system("cls");
                                                    if(l<=5)
                                                    {
                                                        cout<<endl<<"Ubicacion de la lancha "<<l<<endl;
                                                        cout<<endl<<"Ingrese la coordenada donde lo ubicara: ";
                                                        cin>>x;
                                                        cin>>y;
                                                        xau=cordenada(x);
                                                        l=l-1;
                                                    }
                                            }//ciclo de lanchas
                                        }//termina tip 3
                    }//termina el de op<3
            }//termina ciclo de z
			system("cls");
            cout<<endl<<"Comenzo el juego";
            for(i=1;i<=10;i++)
            {
                for(j=1;j<=10;j++)
                {
                    ma12[i][j]=ma2[i][j];
                    ma22[i][j]=ma1[i][j];
                }
            }
            while(dis1<dislim&&dis2<dislim&&final==5)
            {
                z=1;
                cout<<endl<<"Turno del jugador "<<nombres[z];
                cout<<endl<<"Zona del mar propia"<<endl;
                cout<<"   ";
                for(i=1;i<=10;i++)
                {
                    cout<<setw(3)<<m[i];
                }
                cout<<endl;
                for(i=1;i<=10;i++)
                {
                    cout<<setw(3)<<v[i];
                    for(j=1;j<=10;j++)
                    {
                        if(ma1[i][j]==0)
                        {
                            cout<<setw(3)<<"-";
                        }
                        else
                            if(ma1[i][j]==1||ma1[i][j]==2)
                            {
                                cout<<setw(3)<<'P';
                            }
                            else
                                if(ma1[i][j]==3||ma1[i][j]==4||ma1[i][j]==5)
                                {
                                    cout<<setw(3)<<'B';
                                }
                                else
                                    if(ma1[i][j]==99)
                                    {
                                        cout<<setw(3)<<'X';
                                    }
                                    else
                                        if(ma1[i][j]==90||ma1[i][j]==80)
                                        {
                                            cout<<setw(3)<<'O';
                                        }
                                        else
                                        {
                                            cout<<setw(3)<<"L";
                                        }
                    }
                    cout<<endl;
                }
                cout<<endl<<"zona del mar del oponente"<<endl;
                cout<<"   ";
                for(i=1;i<=10;i++)
                {
                    cout<<setw(3)<<m[i];
                }
                cout<<endl;
                for(i=1;i<=10;i++)
                {
                    cout<<setw(3)<<v[i];
                    for(j=1;j<=10;j++)
                    {
                        if(ma12[i][j]==99)
                        {
                            cout<<setw(3)<<"X";
                        }
                        else
                            if(ma12[i][j]==90||ma12[i][j]==80)
                            {
                                cout<<setw(3)<<'O';
                            }
                            else
                            {
                                cout<<setw(3)<<'-';
                            }
                    }
                    cout<<endl;
				}
                cout<<endl<<"indique la coordenada a la cual va a disparar: ";
                cin>>x;
                cin>>y;
                xau=cordenada(x);
                dis1=dis1+1;
                if(juego(ma12,xau,y)==99)
                {
                    cout<<endl<<"?Agua!"<<endl;
                    ma2[xau][y]=99;
                    ma12[xau][y]=99;
                }
                else
                    if(juego(ma12,xau,y)==90)
                    {
                        cout<<endl<<"?Averiado!"<<endl;
                        ma2[xau][y]=90;
                        ma12[xau][y]=90;
                    }
                    else
                        if(juego(ma12,xau,y)==80)
                        {
                            cout<<endl<<"?Hundido!"<<endl;
                            ma2[xau][y]=80;
                            ma12[xau][y]=80;
                        }
                        z=2;
                        cout<<endl<<"turno del jugador "<<nombres[z];
                        cout<<endl<<"Zona del mar propia"<<endl;
                        cout<<"   ";
                        for(i=1;i<=10;i++)
                        {
                            cout<<setw(3)<<m[i];
                        }
                        cout<<endl;
                        for(i=1;i<=10;i++)
                        {
                            cout<<setw(3)<<v[i];
                            for(j=1;j<=10;j++)
                            {
                                if(ma2[i][j]==0)
                                {
                                    cout<<setw(3)<<"-";
                                }
                                else
                                    if(ma2[i][j]==1||ma2[i][j]==2)
                                    {
                                        cout<<setw(3)<<'P';
                                    }
                                    else
                                        if(ma2[i][j]==3||ma2[i][j]==4||ma2[i][j]==5)
                                        {
                                            cout<<setw(3)<<'B';
                                        }
                                        else
                                            if(ma2[i][j]==99)
                                            {
                                                cout<<setw(3)<<'X';
                                            }
                                            else
                                                if(ma2[i][j]==90||ma2[i][k]==80)
                                                {
                                                    cout<<setw(3)<<'O';
                                                }
                                                else
                                                {
                                                    cout<<setw(3)<<'L';
                                                }
                            }
                            cout<<endl;
                        }
                        cout<<endl<<"zona del mar del oponente"<<endl;
                        cout<<"   ";
                        for(i=1;i<=10;i++)
                        {
                            cout<<setw(3)<<m[i];
                        }
                        cout<<endl;
                        for(i=1;i<=10;i++)
                        {
                            cout<<setw(3)<<v[i];
                            for(j=1;j<=10;j++)
                            {
                                if(ma22[i][j]==99)
                                {
                                    cout<<setw(3)<<"X";
                                }
                                else
                                    if(ma22[i][j]==90||ma22[i][j]==80)
                                    {
                                        cout<<setw(3)<<'O';
                                    }
                                    else
                                    {
                                        cout<<setw(3)<<'-';
                                    }
                            }
                            cout<<endl;
                        }
                        cout<<endl<<"indique la coordenada a la cual va a disparar: ";
                        cin>>x;
                        cin>>y;
                        xau=cordenada(x);
                        dis2=dis2+1;
                        if(juego(ma22,xau,y)==99)
                        {
                            cout<<endl<<"?Agua!"<<endl;
                            ma1[xau][y]=99;
                            ma22[xau][y]=99;
                        }
                        else
                            if(juego(ma22,xau,y)==90)
                            {
                                cout<<endl<<"?Averiado!"<<endl;
                                ma1[xau][y]=90;
                                ma22[xau][y]=90;
                            }
                            else
                                if(juego(ma22,xau,y)==80)
                                {
                                    cout<<endl<<"?Hundido!"<<endl;
                                    ma1[xau][y]=80;
                                    ma22[xau][y]=80;
                                }
                                if(casillasacertadas(ma12)==24&&casillasacertadas(ma22)!=24)
                                {
                                    final=1;
                                }
                                else
                                    if(casillasacertadas(ma12)!=24&&casillasacertadas(ma22)==24)
                                    {
                                        final=2;
                                    }
                                    else
                                        if(casillasacertadas(ma12)==24&&casillasacertadas(ma22)==24)
                                        {
                                            final=3;
                                        }
                                        else
                                            if(casillasacertadas(ma12)==casillasacertadas(ma22)&&dis1==dislim&&dis2==dislim)
                                            {
                                                final=4;
                                            }
            }//termin awhile empate
            if(final==1)
            {
                cout<<endl<<"El ganador es el jugador "<<nombres[1];
            }
            else
                if(final==2)
                {
                    cout<<endl<<"El ganador es el jugador "<<nombres[2];
                }
                else
                    if(final==3||final==4)
                    {
                        cout<<endl<<"La partida ha quedado empatada";
                    }
                    cout<<endl<<"Presione 0 para regresar";
                    cin>>h;
        }//termina si menu es = a 1
        else
        if(menu==2)
        {
			system("cls");
            cout<<endl<<"Ingrese su nombre: ";
            cin>>nombres[1];
			system("cls");
			nombres[2][1]='C';nombres[2][2]='P';nombres[2][3]='U';//preguntar, porque no me deja colocar el nombre ya desde el sistema
            z=0;
            while(z<2)
            {
                z=z+1;
                k=0;
                if(z==1)
                {
                    cout<<endl<<"Jugador "<<nombres[1]<<" indique la posicion de sus naves";
                    cout<<endl;
                    cout<<endl<<" Zona del mar propia"<<endl;
                    cout<<"   ";
                    for(i=1;i<=10;i++)
                    {
                        cout<<setw(3)<<m[i];
                    }
                    cout<<endl;                                                                                    
                    for(i=1;i<=10;i++)
                    {
                            cout<<setw(3)<<v[i];
                            for(j=1;j<=10;j++)
                            {
                                if(ma1[i][j]==0)
                                {
                                    cout<<setw(3)<<"-";
                                }
                            }
                        cout<<endl;
                    }
                }
				else
					if(z==2)
					{
						cout<<endl<<"Turno del computador";
					}
                op=0;
                while(op<3)
                {
					op=op+1;
					if(z==1)
					{
						cout<<endl<<"Tipos de naves que deben colocarse"<<endl;
						cout<<"1.Portaviones (2 naves)"<<endl;
						cout<<"2.Bote (3 naves)"<<endl;
						cout<<"3.Lancha (5 naves)"<<endl;
						cout<<endl;
					}
                    if(op==1)
                    {
                        tip=1;
                        if(z==1)
                        {
                            p=1;
                            cout<<endl<<"Ubicacion del portaaviones: "<<p<<endl;//escribir que son 2 porta de 5 esp c/u
                        }
                    }
                    else
                        if(op==2)
                        {
                            tip=2;
                            if(z==1)
                            {    
                                b=1;
                                cout<<endl<<"Ubicacion del Buque "<<b<<endl;
                            }
                                
                        }
                        else
                            if(op==3)
                            {
                                tip=3;
                                if(z==1)
                                {
                                    l=1;
                                    cout<<endl<<"Ubicacion de la lancha "<<l<<endl;
                                }
                            }
					
                            if(tip!=3)
                            {
                                if(z==1)
                                {
                                cout<<endl<<"Ingrese la coordenada donde lo ubicara: ";
                                cin>>x;
                                cin>>y;
                                cout<<endl<<"desea colocarlo 1.Horizontal 2.Vertical: ";
                                cin>>pos;
                                xau=cordenada(x);
                                }
                                else
                                    if(z==2)
                                    {
                                        x=1+rand()%10;
                                        y=1+rand()%10;
                                        pos=1+rand()%2;
                                        xau=x;
                                    }
                            }
                            else
                                if(tip==3)
                                {
                                    if(z==1)
                                    {
                                        cout<<endl<<"Ingrese la coordenada donde lo ubicara: ";
                                        cin>>x;
                                        cin>>y;
                                        xau=cordenada(x);
                                    }
                                    else
                                        if(z==2)
                                        {
                                            x=1+rand()%10;
                                            y=1+rand()%10;
                                            xau=x;
                                        }
                                }
                                if(tip==1)
                                {
                                    p=0;
                                    while(p<=2)
                                    {
                                        p=p+1;
                                        k=k+1;
                                        if(pos==1)
                                        {
                                            if(z==1)
                                            {
                                                if(ma1[xau][y-2]==0&&ma1[xau][y-1]==0&&ma1[xau][y]==0&&ma1[xau][y+1]==0&&ma1[xau][y+2]==0)
                                                {
                                                    for(j=y-2;j<=y+2;j++)
                                                    {
                                                        ma1[xau][j]=k;
                                                    }
                                                }
                                                else
                                                {
                                                    cout<<endl<<"No se puede ubicar el bote en esa posicion, ingrese otra"<<endl;
                                                    p=p-1;
                                                    k=k-1;
                                                }
                                            }
                                            else
                                                if(z==2)
                                                {
                                                    if(ma2[xau][y-2]==0&&ma2[xau][y-1]==0&&ma2[xau][y]==0&&ma2[xau][y+1]==0&&ma2[xau][y+2]==0)
                                                    {
                                                        for(j=y-2;j<=y+2;j++)
                                                        {
                                                            ma2[xau][j]=k;
                                                        }
                                                    }
                                                    else
                                                    {
                                                        p=p-1;
                                                        k=k-1;
                                                    }
                                                }
                                        }
                                        else
                                            if(pos==2)
                                            {
                                                if(z==1)
                                                {
                                                    if(ma1[xau-2][y]==0&&ma1[xau-1][y]==0&&ma1[xau][y]==0&&ma1[xau+1][y]==0&&ma1[xau+2][y]==0)
                                                    {
                                                        for(i=xau-2;i<=xau+2;i++)
                                                        {
                                                            ma1[i][y]=k;
                                                        }
                                                    }
                                                    else
                                                    {
                                                        cout<<endl<<"No se puede ubicar el bote en esa posicion, ingrese otra"<<endl;
                                                        p=p-1;
                                                        k=k-1;
                                                    }
                                                }
                                                else
                                                    if(z==2)
                                                    {
                                                        if(ma2[xau-2][y]==0&&ma2[xau-1][y]==0&&ma2[xau][y]==0&&ma2[xau+1][y]==0&&ma2[xau+2][y]==0)
                                                        {
                                                            for(i=xau-2;i<=xau+2;i++)
                                                            {
                                                                ma2[i][y]=k;
                                                            }
                                                        }
                                                        else
                                                        {
                                                            p=p-1;
                                                            k=k-1;
                                                        }  
                                                    }
                                            }
                                            else
                                            {
                                                cout<<endl<<"Ingrese bien los comandos";
                                                p=p-1;    
                                            }
                                            if(z==1)
                                            {
                                                cout<<"   ";
                                                for(i=1;i<=10;i++)
                                                {
                                                    cout<<setw(3)<<m[i];
                                                }
                                                cout<<endl;
                                                for(i=1;i<=10;i++)
                                                {
                                                    cout<<setw(3)<<v[i];
                                                    for(j=1;j<=10;j++)
                                                    {
                                                        if(ma1[i][j]==0)
                                                        {
                                                            cout<<setw(3)<<"-";
                                                        }
                                                        else
                                                        {
                                                            cout<<setw(3)<<"P";
                                                        }
                                                    }
                                                    cout<<endl;
                                                }
                                            }
                                            p=p+1;
                                            if(p<=2)
                                                {
                                                    if(z==1)
                                                    {
                                                    cout<<endl<<"Ubicacion del portaaviones "<<p<<endl;
                                                    cout<<endl<<"Ingrese la coordenada donde lo ubicara: ";
                                                    cin>>x;
                                                    cin>>y;
                                                    cout<<endl<<"desea colocarlo 1.Horizontal 2.Vertical: ";
                                                    cin>>pos;
                                                    xau=cordenada(x);
                                                    p=p-1;
                                                    }
                                                    else
                                                        if(z==2)
                                                        {
                                                            x=1+rand()%10;
                                                            y=1+rand()%10;
                                                            pos=1+rand()%2;
                                                            xau=x;
                                                            p=p-1;
                                                        }
                                                            
                                                }
                                    }//cierre while porta
                                }//tip 1
                                else
                                    if(tip==2)
                                    {
                                        b=0;
                                        while(b<=3)
                                        {
                                            b=b+1;
                                            k=k+1;
                                            if(pos==1)
                                            {
                                                if(z==1)
                                                {
                                                    if(ma1[xau][y-1]==0&&ma1[xau][y]==0&&ma1[xau][y+1]==0)
                                                    {
                                                        for(j=y-1;j<=y+1;j++)
                                                        {
                                                            ma1[xau][j]=k;
                                                        }
                                                    }
                                                    else
                                                    {
                                                        cout<<endl<<"No se puede ubicar la nave en esa posicion, ingrese otra"<<endl;
                                                        b=b-1;
                                                        k=k-1;
                                                    }
                                                }
                                                else
                                                    if(z==2)
                                                    {
                                                        if(ma2[xau][y-1]==0&&ma2[xau][y]==0&&ma2[xau][y+1]==0)
                                                        {
                                                            for(j=y-1;j<=y+1;j++)
                                                            {
                                                                ma2[xau][j]=k;
                                                            }
                                                        }
                                                        else
                                                        {
                                                            b=b-1;
                                                            k=k-1;
                                                        }  
                                                    }
                                            }
                                            else
                                                if(pos==2)
                                                {
                                                    if(z==1)
                                                    {
                                                        if(ma1[xau-1][y]==0&&ma1[xau][y]==0&&ma1[xau+1][y]==0)
                                                        {
                                                            for(i=xau-1;i<=xau+1;i++)
                                                            {
                                                                ma1[i][y]=k;
                                                            }
                                                        }
                                                        else
                                                        {
                                                            cout<<endl<<"No se puede ubicar la nave en esa posicion, ingrese otra"<<endl;
                                                            b=b-1;
                                                            k=k-1;
                                                        }
                                                    }
                                                    else
                                                        if(z==2)
                                                        {
                                                            if(ma2[xau-1][y]==0&&ma2[xau][y]==0&&ma2[xau+1][y]==0)
                                                            {
                                                                for(i=xau-1;i<=xau+1;i++)
                                                                {
                                                                    ma2[i][y]=k;
                                                                }
                                                            }
                                                            else
                                                            {
                                                                                
                                                                b=b-1;
                                                                k=k-1;
                                                            }
                                                        }
                                                }
                                                else
                                                {
                                                    cout<<endl<<"Ingrese bien los comandos";
                                                    b=b-1;
                                                }
                                                if(z==1)
                                                {
                                                    cout<<"   ";
                                                    for(i=1;i<=10;i++)
                                                    {
                                                        cout<<setw(3)<<m[i];
                                                    }
                                                    cout<<endl;
                                                    for(i=1;i<=10;i++)
                                                    {
                                                        cout<<setw(3)<<v[i];
                                                        for(j=1;j<=10;j++)
                                                        {
                                                            if(ma1[i][j]==0)
                                                            {
                                                                cout<<setw(3)<<"-";
                                                            }
                                                            else
                                                                if(ma1[i][j]==1||ma1[i][j]==2)
                                                                {
                                                                    cout<<setw(3)<<'P';
                                                                }
                                                                else
                                                                {
                                                                    cout<<setw(3)<<"B";
                                                                }
                                                            }
                                                            cout<<endl;
                                                        }
                                                    }
                                                    b=b+1;
                                                    if(b<=3)
                                                    {
                                                        if(z==1)
                                                        {
                                                        cout<<endl<<"Ubicacion del Buque "<<b<<endl;
                                                        cout<<endl<<"Ingrese la coordenada donde lo ubicara: ";
                                                        cin>>x;
                                                        cin>>y;
                                                        cout<<endl<<"desea colocarlo 1.Horizontal 2.Vertical: ";
                                                        cin>>pos;
                                                        xau=cordenada(x);
                                                        b=b-1;
                                                        }
                                                        else
                                                            if(z==2)
                                                            {
                                                                x=1+rand()%10;
                                                                y=1+rand()%10;
                                                                pos=1+rand()%2;
                                                                xau=x;
                                                                b=b-1;
                                                            }
                                                    }
                                        }//cierre while b 3
                                    }//tip 2
                                    else
                                        if(tip==3)
                                        {
                                            l=0;
                                            while(l<=5)
                                            {
                                                l=l+1;
                                                k=k+1;
                                                if(z==1)
                                                {
                                                    if(ma1[xau][y]==0)
                                                    {
                                                        ma1[xau][y]=k;
                                                    }
                                                    else
                                                    {
                                                        cout<<endl<<"No se puede ubicar la nave en esa posicion, ingrese otra"<<endl;
                                                        l=l-1;
                                                        k=k-1;
                                                    }
                                                    cout<<"   ";
                                                    for(i=1;i<=10;i++)
                                                    {
                                                        cout<<setw(3)<<m[i];
                                                    }
                                                    cout<<endl;
                                                    for(i=1;i<=10;i++)
                                                    {
                                                        cout<<setw(3)<<v[i];
                                                        for(j=1;j<=10;j++)
                                                        {
                                                            if(ma1[i][j]==0)
                                                            {
                                                                cout<<setw(3)<<"-";
                                                            }
                                                            else
                                                                if(ma1[i][j]==1||ma1[i][j]==2)
                                                                {
                                                                    cout<<setw(3)<<'P';
                                                                }
                                                                else
                                                                    if(ma1[i][j]==3||ma1[i][j]==4||ma1[i][j]==5)
                                                                    {
                                                                        cout<<setw(3)<<'B';
                                                                    }
                                                                    else
                                                                    {
                                                                        cout<<setw(3)<<"L";
                                                                    }
                                                                }
                                                                cout<<endl;
                                                    }
													l=l+1;
													if(l<=5)
													{
														cout<<endl<<"Ubicacion de la lancha "<<l<<endl;
														cout<<endl<<"Ingrese la coordenada donde lo ubicara: ";
														cin>>x;
														cin>>y;
														xau=cordenada(x);
														l=l-1;
													}
                                                                                                                              
                                                }
                                                else
                                                    if(z==2)
                                                    {
                                                        if(ma2[xau][y]==0)
                                                        {
                                                            ma2[xau][y]=k;
                                                        }
                                                        else
                                                        {                                        
                                                            l=l-1;
                                                            k=k-1;
                                                        }
                                                        l=l+1;
                                                        if(l<=5)
                                                        {
                                                            x=1+rand()%10;//fgfgfg
                                                            y=1+rand()%10;
                                                            xau=x;
                                                            l=l-1;      
                                                        }
                                                    }
                                            }//termina while lancha 5
                                        }//termina tip3
                }//fin while op
            }//cierre while z<=2
            cout<<endl<<"Comenzo el juego";
            for(i=1;i<=10;i++)
            {
                for(j=1;j<=10;j++)
                {
                    ma12[i][j]=ma2[i][j];
                    ma22[i][j]=ma1[i][j];
                }
            }
            while(dis1<dislim&&dis2<dislim&&final==5)
            {
                z=1;
                cout<<endl<<"Turno del jugador "<<nombres[z];
                cout<<endl<<"Zona del mar propia"<<endl;
                cout<<"   ";
                for(i=1;i<=10;i++)
                {
                    cout<<setw(3)<<m[i];
                }
                cout<<endl;
                for(i=1;i<=10;i++)
                {
                    cout<<setw(3)<<v[i];
                    for(j=1;j<=10;j++)
                    {
                        if(ma1[i][j]==0)
                        {
                            cout<<setw(3)<<"-";
                        }
                        else
                            if(ma1[i][j]==1||ma1[i][j]==2)
                            {
                                cout<<setw(3)<<'P';
                            }
                            else
                                if(ma1[i][j]==3||ma1[i][j]==4||ma1[i][j]==5)
                                {
                                    cout<<setw(3)<<'B';
                                }
                                else
                                    if(ma1[i][j]==99)
                                    {
                                        cout<<setw(3)<<'X';
                                    }
                                    else
                                        if(ma1[i][j]==90||ma1[i][j]==80)
                                        {
                                            cout<<setw(3)<<'O';
                                        }
                                        else
                                        {
                                            cout<<setw(3)<<"L";
                                        }
                    }
                    cout<<endl;
                }
                cout<<endl<<"zona del mar del oponente"<<endl;
                cout<<"   ";
                for(i=1;i<=10;i++)
                {
                    cout<<setw(3)<<m[i];
                }
                cout<<endl;
                for(i=1;i<=10;i++)
                {
                    cout<<setw(3)<<v[i];
                    for(j=1;j<=10;j++)
                    {
                        if(ma12[i][j]==99)
                        {
                            cout<<setw(3)<<"X";
                        }
                        else
                            if(ma12[i][j]==90||ma12[i][j]==80)
                            {
                                cout<<setw(3)<<'O';
                            }
                            else
                            {
                                cout<<setw(3)<<'-';
                            }
                    }
                    cout<<endl;
                }
                cout<<endl<<"indique la coordenada a la cual va a disparar: ";
                cin>>x;
                cin>>y;
                xau=cordenada(x);
                cout<<endl<<"indique la coordenada a la cual va a disparar: ";
                cin>>x;
                cin>>y;
                xau=cordenada(x);
                dis1=dis1+1;
                if(juego(ma12,xau,y)==99)
                {
                    cout<<endl<<"?Agua!"<<endl;
                    ma2[xau][y]=99;
                    ma12[xau][y]=99;
                }
                else
                    if(juego(ma12,xau,y)==90)
                    {
                        cout<<endl<<"?Averiado!"<<endl;
                        ma2[xau][y]=90;
                        ma12[xau][y]=90;
                    }
                    else
                        if(juego(ma12,xau,y)==80)
                        {
                            cout<<endl<<"?Hundido!"<<endl;
                            ma2[xau][y]=80;
                            ma12[xau][y]=80;
                        }
                        z=2;
                        cout<<endl<<"turno del jugador "<<nombres[z];
                        x=1+rand()%10;
                        y=1+rand()%10;
                        xau=cordenada(x);
                        dis2=dis2+1;
                        if(juego(ma22,xau,y)==99)
                        {
                            cout<<endl<<"?Agua!"<<endl;
                            ma1[xau][y]=99;
                            ma22[xau][y]=99;
                        }
                        else
                            if(juego(ma22,xau,y)==90)
                            {
                                cout<<endl<<"?Averiado!"<<endl;
                                ma1[xau][y]=90;
                                ma22[xau][y]=90;
                            }
                            else
                                if(juego(ma22,xau,y)==80)
                                {
                                    cout<<endl<<"?Hundido!"<<endl;
                                    ma1[xau][y]=80;
                                    ma22[xau][y]=80;
                                }
                                if(casillasacertadas(ma12)==24&&casillasacertadas(ma22)!=24)
                                {
                                    final=1;
                                }
                                else
                                    if(casillasacertadas(ma12)!=24&&casillasacertadas(ma22)==24)
                                    {
                                        final=2;
                                    }
                                    else
                                        if(casillasacertadas(ma12)==24&&casillasacertadas(ma22)==24)
                                        {
                                            final=3;
                                        }
                                        else
                                            if(casillasacertadas(ma12)==casillasacertadas(ma22)&&dis1==dislim&&dis2==dislim)
                                            {
                                                final=4;
                                            }

            }//while de empate
            if(final==1)
            {
                cout<<endl<<"El ganador es el jugador "<<nombres[1];
            }
            else
                if(final==2)
                {
                    cout<<endl<<"El ganador es el jugador "<<nombres[2];
                }
                else
                    if(final==3||final==4)
                    {
                        cout<<endl<<"La partida ha quedado empatada";
                    }
                    cout<<endl<<"Presione 0 para regresar";
                    cin>>h;
        }//termina menu==2
    }//termina menu
    cout<<endl<<endl<<endl<<endl<<endl<<endl<<endl;
    cout<<"                                 Se ha cerrado la aplicacion";
    _getch();
}//aqui termina